# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3a2ff6c5aadfe7d04be74d8536b7a909a1cae63013f1487381eb31312a31e9e19c7e30090d4c3d22cf06c1ae445eddb2dd874ac10ad01d881e5fc72543a4d6e

test:
  secret_key_base: 7b3cac20c7ad0d55ac5d403a94883440682f3efc2018926ccd0ea5ef69a178db618302965258c96384abce61d686bf5f2690cd8996c81a65ae6fc0c568861263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
